name: Draft PDF

on:
  workflow_dispatch:  # Manual trigger only for testing
  push:
    paths: 
      - 'paper/**'

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Generate draft PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Validate paper structure
        run: |
          echo "=== Checking paper structure ==="
          ls -la paper/
          echo ""
          echo "=== Paper.md first 20 lines ==="
          head -20 paper/paper.md
          echo ""
          echo "=== Bibliography check ==="
          head -5 paper/paper.bib
          
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
          
      - name: Debug output locations
        if: always()
        run: |
          echo "=== Searching for generated files ==="
          find . -name "*.pdf" -type f 2>/dev/null || echo "No PDF files found"
          find . -name "*.log" -type f 2>/dev/null || echo "No log files found"
          echo ""
          echo "=== Working directory ==="
          pwd
          ls -la
          
      - name: Upload draft PDF
        uses: actions/upload-artifact@v4
        if: hashFiles('paper.pdf') != ''
        with:
          name: draft-pdf
          path: paper.pdf
          
      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: all-outputs
          path: |
            ./**/*.pdf
            ./**/*.log
            ./paper.*
          if-no-files-found: ignore