name: Draft PDF

on:
  push:
    branches: [ main ]
    paths: 
      - 'paper/**'
      - '.github/workflows/draft-pdf.yml'
  pull_request:
    branches: [ main ]
    paths: 
      - 'paper/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Generate draft PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper/paper.md
          
      - name: List generated files
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Files in paper directory:"
          ls -la paper/
          find . -name "*.pdf" -type f
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: draft-paper-pdf
          path: |
            paper.pdf
            ./paper.pdf
            paper/paper.pdf
            
      - name: Upload all logs and outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pdf-generation-logs
          path: |
            paper.log
            ./paper.log
            paper/paper.log
            *.log